import {
  PersonSimpleWalk,
  PersonSimpleRun,
  PersonSimpleBike,
  PersonSimpleHike,
  PersonSimpleSwim,
  PersonSimpleTaiChi,
  PersonSimpleSki,
  PersonSimpleSnowboard,
  PersonArmsSpread,
  PersonSimple,
  Barbell,
  Bicycle,
  Basketball,
  Baseball,
  Football,
  SoccerBall,
  TennisBall,
  Volleyball,
  BoxingGlove,
  Sneaker,
  SneakerMove,
  SwimmingPool,
  Mountains,
  Wheelchair,
  Heartbeat,
  Gauge,
  Stairs,
  Trophy,
  Lightning,
  Wind,
  Flame,
  MapTrifold,
  DotsThreeCircle,
  type Icon,
} from '@phosphor-icons/react'

export const ACTIVITY_ICONS: Record<string, Icon> = {
  PersonSimpleWalk,
  PersonSimpleRun,
  PersonSimpleBike,
  PersonSimpleHike,
  PersonSimpleSwim,
  PersonSimpleTaiChi,
  PersonSimpleSki,
  PersonSimpleSnowboard,
  PersonArmsSpread,
  PersonSimple,
  Barbell,
  Bicycle,
  Basketball,
  Baseball,
  Football,
  SoccerBall,
  TennisBall,
  Volleyball,
  BoxingGlove,
  Sneaker,
  SneakerMove,
  SwimmingPool,
  Mountains,
  Wheelchair,
  Heartbeat,
  Gauge,
  Stairs,
  Trophy,
  Lightning,
  Wind,
  Flame,
  MapTrifold,
  DotsThreeCircle,
}

// Curated, labelled options for the activity icon picker — covers common
// gym/cardio/sport activities so users don't need to know Phosphor icon names.
export const ACTIVITY_ICON_OPTIONS: { name: keyof typeof ACTIVITY_ICONS; label: string }[] = [
  { name: 'PersonSimpleRun', label: 'Running' },
  { name: 'Gauge', label: 'Treadmill' },
  { name: 'SneakerMove', label: 'Jogging' },
  { name: 'PersonSimpleWalk', label: 'Walking' },
  { name: 'PersonSimpleHike', label: 'Hiking' },
  { name: 'Mountains', label: 'Climbing' },
  { name: 'PersonSimpleBike', label: 'Cycling' },
  { name: 'Bicycle', label: 'Bike' },
  { name: 'PersonSimpleSwim', label: 'Swimming' },
  { name: 'SwimmingPool', label: 'Pool' },
  { name: 'PersonSimpleSki', label: 'Skiing' },
  { name: 'PersonSimpleSnowboard', label: 'Snowboarding' },
  { name: 'PersonSimpleTaiChi', label: 'Yoga' },
  { name: 'PersonArmsSpread', label: 'Stretching' },
  { name: 'Barbell', label: 'Weights' },
  { name: 'BoxingGlove', label: 'Boxing' },
  { name: 'Basketball', label: 'Basketball' },
  { name: 'Football', label: 'Football' },
  { name: 'SoccerBall', label: 'Soccer' },
  { name: 'TennisBall', label: 'Tennis' },
  { name: 'Volleyball', label: 'Volleyball' },
  { name: 'Baseball', label: 'Baseball' },
  { name: 'Wheelchair', label: 'Wheelchair' },
  { name: 'Stairs', label: 'Stairs' },
  { name: 'Sneaker', label: 'Shoes' },
  { name: 'Heartbeat', label: 'Cardio' },
  { name: 'Lightning', label: 'HIIT' },
  { name: 'Wind', label: 'Endurance' },
  { name: 'Flame', label: 'Burn' },
  { name: 'MapTrifold', label: 'Route' },
  { name: 'Trophy', label: 'Sport' },
  { name: 'PersonSimple', label: 'Other' },
]

export function getActivityIcon(name: string): Icon {
  return ACTIVITY_ICONS[name] ?? DotsThreeCircle
}
