/**
 * BF-122b / BF-126 — the sprite layer, isolated so replacing it is one file.
 *
 * **Art first, glyph as the fallback.** Each tier maps to a drawn SVG in `public/cats/` (generated by
 * `scripts/collection-art/build.mjs`) and to an emoji. `CatSprite` shows the art and drops to the
 * glyph if the file fails to load — offline before the service worker has cached it, say — so a
 * tier is never left empty.
 *
 * **The drawn set is per class, including the bottom rung.** The owner's 2026-09-26 brief gave each
 * faucet its own MMO class with its own tier-1 cat, which retires the old "one shared slime" rule
 * for the art. The glyphs keep the shared bottom rung because the engine still names it `cat slime`
 * on every ladder; that changes with the rules rewrite, not here.
 *
 * The art is drawn to read at ~56 px, not the 32 px an emoji is designed for — detail at 32 px is
 * what BF-126 warned would look worse than the glyph, so the render sites size up to match.
 */
import type { FaucetKey } from './collection-summary'

/** Tier index within its ladder → the glyph shown for it. Bottom rung first. */
const GLYPHS: Record<FaucetKey, string[]> = {
  workout: ['🐱', '🐈', '🛡️'],
  steps: ['🐱', '🐈', '🏹'],
  sleep: ['🐱', '🐈', '🔮'],
}

/**
 * The seven drawn classes, one per category the collection can track. The full catalogue — which
 * category each class is for, and which are wired to a ladder — is
 * `docs/domains/app-shell/cat-collection-design-catalog.md`.
 */
export type CatClass = 'tank' | 'ranger' | 'rogue' | 'cleric' | 'mage' | 'alchemist' | 'monk'
export const CAT_CLASSES: readonly CatClass[] = ['tank', 'ranger', 'rogue', 'cleric', 'mage', 'alchemist', 'monk']
/** Six drawn tiers per class. */
export const ART_TIERS = 6
/** Every tier of every class also exists in these coats: a rare `shiny` and two award skins. */
export type CatVariant = 'shiny' | 'frost' | 'ember'
export const CAT_VARIANTS: readonly CatVariant[] = ['shiny', 'frost', 'ember']

/** Which class each existing ladder is drawn as. Sleep is the Mage's; the Health cat waits for its logging ladder. */
export const LADDER_CLASS: Record<FaucetKey, CatClass> = {
  workout: 'tank',
  steps: 'ranger',
  sleep: 'mage',
}

export function tierGlyph(faucet: FaucetKey, tier: number): string {
  return GLYPHS[faucet][tier] ?? GLYPHS[faucet][0]
}

export function ladderGlyphs(faucet: FaucetKey): readonly string[] {
  return GLYPHS[faucet]
}

/** Path to any class's sprite, or null past the top of the drawn set. */
export function classArt(cls: CatClass, tier: number, variant?: CatVariant): string | null {
  if (tier < 0 || tier >= ART_TIERS) return null
  return `/cats/${cls}-${tier + 1}${variant ? `-${variant}` : ''}.svg`
}

/** Path to the drawn sprite for a ladder tier, or null past the top of the drawn set. */
export function tierArt(faucet: FaucetKey, tier: number, variant?: CatVariant): string | null {
  return classArt(LADDER_CLASS[faucet], tier, variant)
}
