/**
 * BF-122b / BF-126 — the sprite layer, isolated so replacing it is one file.
 *
 * **Art first, glyph as the fallback.** Each tier maps to a drawn SVG in `public/cats/` (generated by
 * `scripts/collection-art/build.mjs`) and to an emoji. `CatSprite` shows the art and drops to the
 * glyph if the file fails to load — offline before the service worker has cached it, say — so a
 * tier is never left empty.
 *
 * **The drawn set is per class, including the bottom rung.** The owner's 2026-09-26 brief gave each
 * faucet its own MMO class with its own tier-1 cat, which retires the old "one shared slime" rule
 * for the art. The glyphs keep the shared bottom rung because the engine still names it `cat slime`
 * on every ladder; that changes with the rules rewrite, not here.
 *
 * The art is drawn to read at ~56 px, not the 32 px an emoji is designed for — detail at 32 px is
 * what BF-126 warned would look worse than the glyph, so the render sites size up to match.
 */
import type { FaucetKey } from './collection-summary'

/** Tier index within its ladder → the glyph shown for it. Bottom rung first. */
const GLYPHS: Record<FaucetKey, string[]> = {
  workout: ['🐱', '🐈', '🛡️'],
  steps: ['🐱', '🐈', '🏹'],
  sleep: ['🐱', '🐈', '🔮'],
}

/** The four drawn classes. `rogue` (cardio) has art and no ladder yet; `cleric` is drawn for the Health cat. */
export type CatClass = 'tank' | 'ranger' | 'rogue' | 'cleric'
/** Six drawn tiers per class, each with a rare `-shiny` recolour. */
export const ART_TIERS = 6

/** Which class each existing ladder is drawn as. Sleep stands in for the Cleric's tracking faucet. */
export const LADDER_CLASS: Record<FaucetKey, CatClass> = {
  workout: 'tank',
  steps: 'ranger',
  sleep: 'cleric',
}

export function tierGlyph(faucet: FaucetKey, tier: number): string {
  return GLYPHS[faucet][tier] ?? GLYPHS[faucet][0]
}

export function ladderGlyphs(faucet: FaucetKey): readonly string[] {
  return GLYPHS[faucet]
}

/** Path to the drawn sprite for a ladder tier, or null past the top of the drawn set. */
export function tierArt(faucet: FaucetKey, tier: number, shiny = false): string | null {
  if (tier < 0 || tier >= ART_TIERS) return null
  return `/cats/${LADDER_CLASS[faucet]}-${tier + 1}${shiny ? '-shiny' : ''}.svg`
}
