// issue 2700 — a commit message that carries AI attribution fails the Custom Rules step.
// The fixture is a throwaway repository: `origin/main` points at a clean base commit, and each case
// adds one commit on top, so the local fallback (`origin/main..HEAD`) is the path under test.
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { execFileSync, spawnSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

const script = path.join(__dirname, '..', 'check-commit-attribution.js')
let repo: string
let scratch: string

const git = (...args: string[]) =>
  execFileSync('git', args, { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()

function commit(message: string) {
  writeFileSync(path.join(repo, 'f.txt'), `${Math.random()}\n`)
  git('add', '.')
  const msgFile = path.join(scratch, 'msg.txt')
  writeFileSync(msgFile, message)
  git('commit', '-q', '-F', msgFile)
}

function run(overrides: Record<string, string> = {}, cwd = repo) {
  const env = { ...process.env }
  delete env.PR_BASE_SHA
  delete env.PR_HEAD_SHA
  delete env.PR_COMMITS
  return spawnSync('node', [script, '--repo', cwd], { encoding: 'utf8', env: { ...env, ...overrides } })
}

function commitTree(message: string, ...parents: string[]) {
  return execFileSync('git', ['commit-tree', 'HEAD^{tree}', ...parents.flatMap(sha => ['-p', sha])], {
    cwd: repo, encoding: 'utf8', input: message,
  }).trim()
}

beforeAll(() => {
  scratch = mkdtempSync(path.join(os.tmpdir(), 'attribution-'))
  repo = path.join(scratch, 'repo')
  execFileSync('git', ['init', '-q', '-b', 'work', repo])
  git('config', 'user.email', 't@example.com')
  git('config', 'user.name', 'T')
  git('config', 'commit.gpgsign', 'false')
  commit('base commit\n\nCo-authored-by: Claude <noreply@anthropic.com>\n') // history is exempt
  git('update-ref', 'refs/remotes/origin/main', 'HEAD')
})
afterAll(() => rmSync(scratch, { recursive: true, force: true }))

describe('check-commit-attribution', () => {
  it('passes when no commit is ahead of origin/main', () => {
    expect(run().status).toBe(0)
  })

  it('passes a clean commit', () => {
    commit('Fix the thing\n\nIt broke because of a stale cache.\n')
    const res = run()
    expect(res.status).toBe(0)
    expect(res.stdout).toContain('none carries AI attribution')
  })

  it('passes a human co-author line', () => {
    commit('Pair on the fix\n\nCo-authored-by: Delan Dasanayake <delan@example.com>\n')
    expect(run().status).toBe(0)
  })

  it.each([
    ['AI co-author trailer', 'Co-authored-by: Claude <noreply@anthropic.com>'],
    ['AI co-author trailer', 'Co-authored-by: Bot <bot@noreply@anthropic.com>'],
    ['Claude session URL', 'Claude-Session: https://claude.ai/code/session_abc123'],
    ['"Generated with/by Claude" line', 'Generated with [Claude Code](https://claude.com/claude-code)'],
    ['"Generated with/by Claude" line', 'Generated by Claude'],
  ])('fails %s, naming the commit, the line and the fix', (pattern, line) => {
    commit(`Offending commit\n\nA body.\n\n${line}\n`)
    const sha = git('rev-parse', 'HEAD').slice(0, 10)
    const res = run()
    git('reset', '-q', '--hard', 'HEAD~1')
    expect(res.status).toBe(1)
    expect(res.stderr).toContain(sha)
    expect(res.stderr).toContain('Offending commit')
    expect(res.stderr).toContain(line)
    expect(res.stderr).toContain(pattern)
    expect(res.stderr).toContain('git commit --amend')
  })

  it('checks only PR commits after merging a base with AI attribution', () => {
    const base = commitTree('Main change\n\nCo-authored-by: Claude <noreply@anthropic.com>\n', git('rev-parse', 'origin/main'))
    const head = commitTree('Merge main\n', git('rev-parse', 'HEAD'), base)
    const res = run({ PR_BASE_SHA: base, PR_HEAD_SHA: head, PR_COMMITS: '3' })
    expect(res.status).toBe(0)
    expect(res.stdout).toContain('3 commit(s)')

    const offending = commitTree('PR change\n\nCo-authored-by: Claude <noreply@anthropic.com>\n', head)
    const rejected = run({ PR_BASE_SHA: base, PR_HEAD_SHA: offending, PR_COMMITS: '4' })
    expect(rejected.status).toBe(1)
    expect(rejected.stderr).toContain(offending.slice(0, 10))
    expect(rejected.stderr).not.toContain(base.slice(0, 10))
  })

  it('fails when CI cannot identify every PR commit', () => {
    const env = { PR_BASE_SHA: git('rev-parse', 'origin/main'), PR_HEAD_SHA: git('rev-parse', 'HEAD'), PR_COMMITS: '2' }
    expect(run({ ...env, PR_BASE_SHA: '' }).status).toBe(1)
    expect(run({ ...env, PR_BASE_SHA: 'f'.repeat(40) }).status).toBe(1)
    expect(run({ ...env, PR_COMMITS: '3' }).stderr).toContain('expected 3 PR commits, found 2')
  })

  it('rejects a shallow CI checkout instead of overlooking missing history', () => {
    const shallow = path.join(scratch, 'shallow')
    execFileSync('git', ['clone', '-q', '--depth=1', '--no-checkout', pathToFileURL(repo).href, shallow])
    const res = run({ PR_BASE_SHA: git('rev-parse', 'origin/main'), PR_HEAD_SHA: git('rev-parse', 'HEAD'), PR_COMMITS: '2' }, shallow)
    expect(res.status).toBe(1)
    expect(res.stderr).toContain('full-history checkout')
  })

  it('skips, passing, when there is no base to compare against', () => {
    git('update-ref', '-d', 'refs/remotes/origin/main')
    const res = run()
    expect(res.status).toBe(0)
    expect(res.stdout).toContain('skipped')
  })
})
