-- 034_clear_gif_cache.sql
-- Clears the auto-generated GIF cache so all exercises are re-matched on
-- the next admin sync. Required after fixing the step-3 matching logic which
-- was returning the first (not most specific) dataset exercise for single-word
-- search terms, causing wrong GIFs (e.g. "squat" → Bulgarian split squat).
-- The cache is fully regenerated by the admin → Exercises → sync (refresh) button.

TRUNCATE exercise_gif_cache;
