-- Audit finding Q-12: bodyweight `estimated_1rm` history holds two incommensurable eras.
--
-- `estimateOneRm` prices a bodyweight set at `BW_REF + addedKg` with BW_REF a FIXED 100
-- (lib/1rm.ts), so the value is a pure function of reps. Before that constant landed (the data
-- boundary is between 2026-06-28 and 2026-07-05) the same code used the lifter's real weigh-in,
-- which drifted 67.6–72.8 kg over the window. The result: Pull-Up "1RM" read 82.0 on 2026-06-28
-- and 114.5 on 2026-07-05 — +39.6% on *equal or fewer* reps per set, entirely a change of
-- constant. It was recorded as a real PR, and it feeds the prescription engine's 1RM-trend term.
--
-- This rebases the pre-changeover rows onto BW_REF = 100 so the whole series is comparable.
-- No rep count and no logged weight is touched — only the derived estimate, and only where it
-- still holds exactly the value the old constant produced.
--
-- The replacement values were generated by the real module, never reimplemented in SQL:
--
--     estimateOneRm(reps.map(r => ({ weightKg: 0, reps: r })),
--                   { exerciseType: 'bodyweight', bwRef: 100 })
--
-- Every one of the 7 post-changeover rows reproduces its stored value EXACTLY under that call,
-- which is what identifies the boundary; none of these 6 do. All 13 bodyweight logs in the
-- history carry addedKg = 0.
--
-- Reversible: each row's pre-migration (estimated_1rm, target_80) pair is recorded below, and
-- the guard means re-running is a no-op.

UPDATE exercise_logs el
SET estimated_1rm = v.new_1rm,
    target_80     = v.new_t80,
    updated_at    = now()
FROM (VALUES
  ('101055ec-6184-470c-a8ae-ed046b1fc03b'::uuid,  78.75,  63.00, 114.50,  91.50),  -- Pull-Up           2026-06-11  reps 5
  ('3245917b-c8d3-403f-8409-cc347cb1ff29'::uuid,  80.50,  64.50, 109.75,  87.75),  -- Pull-Up           2026-06-17  reps 4,4,3,3
  ('a80ccdf7-264a-4fc6-a036-79c8fb16802e'::uuid,  82.75,  66.25, 118.00,  94.50),  -- Pull-Up           2026-06-21  reps 7
  ('c3f52c76-e253-4d61-90a6-22b94f026d79'::uuid,  93.75,  75.00, 128.00, 102.50),  -- Hanging Leg Raise 2026-06-23  reps 11
  ('54d8ecff-703d-483e-a4f7-67b4530b0da0'::uuid,  82.00,  65.50, 113.00,  90.50),  -- Pull-Up           2026-06-28  reps 5,4,4,5
  ('a7126cb3-b5e4-4f37-9682-92bc677000a0'::uuid, 104.75,  83.75, 124.00,  99.25)   -- Hanging Leg Raise 2026-06-29  reps 10,10,10
) AS v(id, old_1rm, old_t80, new_1rm, new_t80)
WHERE el.id = v.id
  -- Idempotent, and a no-op on any row that has since been edited: only rewrite a value that is
  -- still exactly what the old constant produced.
  AND abs(el.estimated_1rm - v.old_1rm) < 0.005
  AND el.deleted_at IS NULL;

-- The two bodyweight PRs both point at the changeover session, so they are phantoms: Pull-Up at
-- 114.5 (2026-07-05) and Hanging Leg Raise at 123.25 (2026-07-07) were the first rows priced at
-- the new constant, not the best performances. Re-derive them from the corrected logs.
--
-- Pure aggregation over the column the statement above just fixed — the 1RM formula is not
-- restated here. The gate mirrors `reconcilePersonalRecord` (adapter.ts): skip per-exercise
-- deloads, skip deload/early-deload sessions, but let a NULL phase_type count as "not deload"
-- (manual-mode programs never set it), and break ties on the EARLIEST log so a PR keeps the date
-- it was first proved.
WITH best AS (
  -- Partitioned by user_id as well as exercise_name: a bare DISTINCT ON (exercise_name) would
  -- pick one row across ALL accounts and stamp it onto every user's PR for that movement.
  SELECT DISTINCT ON (ws.user_id, el.exercise_name)
         ws.user_id, el.exercise_name, el.estimated_1rm, el.logged_at
  FROM exercise_logs el
  JOIN workout_sessions ws ON ws.id = el.workout_session_id
  WHERE el.deleted_at IS NULL
    AND ws.deleted_at IS NULL
    AND el.estimated_1rm > 0
    AND el.exercise_deloaded = false
    AND (ws.phase_type = 'baseline'
         OR ((ws.phase_type IS NULL OR ws.phase_type <> 'deload') AND ws.is_early_deload = false))
    AND el.exercise_name IN (SELECT name FROM exercise_library WHERE exercise_type = 'bodyweight')
  ORDER BY ws.user_id, el.exercise_name, el.estimated_1rm DESC, el.logged_at ASC
)
UPDATE personal_records pr
SET estimated_1rm = best.estimated_1rm,
    achieved_at   = best.logged_at
FROM best
WHERE pr.user_id = best.user_id
  AND pr.exercise_name = best.exercise_name
  AND (abs(pr.estimated_1rm - best.estimated_1rm) > 0.005 OR pr.achieved_at <> best.logged_at);
