-- Audit finding Q-13: bodyweight sets recorded ZERO volume.
--
-- `log-exercise.ts` priced a bodyweight set at `BW_REF + added` for the 1RM and the intensity
-- percentage, but computed volume from the RAW logged weight — which is 0 for an unloaded
-- bodyweight set, three lines apart in the same function. So the same rows simultaneously read as
-- 82–88% intensity and zero work done, and 208 real reps (19 Pull-Up sets, 13 Hanging Leg Raise
-- sets) were absent from lifetime volume, weekly volume, `computeVolumeAcwr` — which gates the
-- early-deload recommendation — and the prescription engine's own volume budget.
--
-- Owner decision (2026-07-27): price a bodyweight rep at the lifter's REAL body weight times a
-- per-exercise fraction. Deliberately NOT `BW_REF`: that constant exists so the 1RM estimate stops
-- tracking weigh-ins, and reusing it here would put ~100 kg on every rep and let bodyweight work
-- dominate the totals (20,800 kg rather than the 8,856 kg below).
--
-- The values were generated by the real module, never reimplemented in SQL:
--
--     bodyweightSetLoadKg(exerciseName, bodyweightKg, addedKg)   // lib/workout/bodyweight-load.ts
--
-- with `bodyweightKg` taken from the most recent weigh-in at or before each session — the same
-- lookup the live write path now performs. Factors: Pull-Up 1.00 (whole body suspended), Hanging
-- Leg Raise 0.32 (both legs ≈ 32% of body mass, Dempster/Winter segmental fractions).
--
-- NOTE — a deliberate invariant change. Before this, `exercise_logs.volume` always equalled
-- Σ(set_logs.weight_kg × reps); the first production audit verified that on all 288 logs. These 13
-- rows will no longer satisfy it, because `set_logs.weight_kg` correctly records what was on the
-- BAR (0 kg) while volume now records work DONE. Any future check of that invariant must exempt
-- bodyweight exercises rather than "correct" these rows back to zero.
--
-- Reversible: every pre-migration value was 0, so `SET volume = 0` for these ids restores it.
-- Idempotent: the guard only ever rewrites a row still sitting at 0.

UPDATE exercise_logs el
SET volume = v.volume,
    updated_at = now()
FROM (VALUES
  ('c3f52c76-e253-4d61-90a6-22b94f026d79'::uuid,  240.06),  -- Hanging Leg Raise 2026-06-23   11 reps × 21.82 kg
  ('a7126cb3-b5e4-4f37-9682-92bc677000a0'::uuid,  653.76),  -- Hanging Leg Raise 2026-06-29   30 reps × 21.79 kg
  ('63a245c6-a298-413a-a10c-5b2cf56122ba'::uuid,  612.86),  -- Hanging Leg Raise 2026-07-07   28 reps × 21.89 kg
  ('f03a3593-036a-45cf-be24-ff1d035d46ee'::uuid,  525.31),  -- Hanging Leg Raise 2026-07-14   24 reps × 21.89 kg
  ('e52db704-9180-4260-80a2-2f1102108f14'::uuid,  481.54),  -- Hanging Leg Raise 2026-07-21   22 reps × 21.89 kg
  ('101055ec-6184-470c-a8ae-ed046b1fc03b'::uuid,  344.00),  -- Pull-Up           2026-06-11    5 reps × 68.80 kg
  ('3245917b-c8d3-403f-8409-cc347cb1ff29'::uuid,  956.20),  -- Pull-Up           2026-06-17   14 reps × 68.30 kg
  ('a80ccdf7-264a-4fc6-a036-79c8fb16802e'::uuid,  473.90),  -- Pull-Up           2026-06-21    7 reps × 67.70 kg
  ('54d8ecff-703d-483e-a4f7-67b4530b0da0'::uuid, 1216.80),  -- Pull-Up           2026-06-28   18 reps × 67.60 kg
  ('558be40b-efcc-454f-8fbb-7fd0a3389719'::uuid, 1026.00),  -- Pull-Up           2026-07-05   15 reps × 68.40 kg
  ('19c79cbb-8ba6-4f64-af88-7e08b88ccd8f'::uuid, 1231.20),  -- Pull-Up           2026-07-12   18 reps × 68.40 kg
  ('9f10b472-c9d4-4096-bd38-db74fcc115e9'::uuid,  410.40),  -- Pull-Up           2026-07-19    6 reps × 68.40 kg
  ('5e0a9a14-262d-48d8-b0ea-0f317e723bca'::uuid,  684.00)   -- Pull-Up           2026-07-26   10 reps × 68.40 kg
) AS v(id, volume)
WHERE el.id = v.id
  AND COALESCE(el.volume, 0) = 0     -- only ever fills a zero; a re-run is a no-op
  AND el.deleted_at IS NULL;

-- `user_stats` derives its totals from these rows (reconcileUserStats), so lifetime volume picks
-- the change up on its next read — no counter to update here.
