-- GENERATED by scripts/generate-claude-ro-views.js — do not hand-edit.
-- Read-only view surface for the claude_readonly role (default-deny: a table with no
-- view here is unreadable). Plan: docs/superpowers/plans/2026-07-26-claude-readonly-prod-db-access.md

DROP SCHEMA IF EXISTS claude_ro CASCADE;
CREATE SCHEMA claude_ro;

CREATE VIEW claude_ro.activity_logs AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.activity_type,
  t.title,
  t.start_time,
  t.end_time,
  t.duration_min,
  t.distance_km,
  t.calories_burned,
  t.avg_hr,
  t.max_hr,
  t.notes,
  t.created_at,
  t.route_polyline,
  t.splits,
  t.best_efforts,
  t.pace_series,
  t.avg_pace_sec_per_km,
  t.elevation_gain_m,
  t.elevation_loss_m,
  t.updated_at,
  t.steps,
  t.deleted_at,
  t.cadence_spm,
  t.cadence_series,
  t.cadence_source,
  t.elevation_profile,
  t.segments
FROM public.activity_logs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- activity_types: shared reference data, not row-scoped
CREATE VIEW claude_ro.activity_types AS
SELECT
  t.id,
  t.label,
  t.icon,
  t.is_distance_based,
  t.sort_order,
  t.created_at
FROM public.activity_types t;

CREATE VIEW claude_ro.ai_call_log AS
SELECT
  t.id,
  t.user_id,
  t.section,
  t.model,
  t.input_tokens,
  t.output_tokens,
  t.total_tokens,
  t.latency_ms,
  t.ok,
  t.fingerprint,
  t.created_at
FROM public.ai_call_log t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.ai_health_insights AS
SELECT
  t.id,
  t.user_id,
  t.section,
  t.date,
  t.insight,
  t.created_at,
  t.context_hash
FROM public.ai_health_insights t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.body_battery_daily AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.anchor,
  t.anchor_source,
  t.end_value,
  t.day_min,
  t.day_max,
  t.total_charged,
  t.total_drained,
  t.resting_hr,
  t.hr_max,
  t.hr_max_observed,
  t.hr_sample_count,
  t.model_version,
  t.computed_at,
  t.updated_at
FROM public.body_battery_daily t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.body_metrics AS
SELECT
  t.id,
  t.date,
  t.weight_kg,
  t.body_fat_pct,
  t.calories,
  t.protein_g,
  t.carbs_g,
  t.fat_g,
  t.steps,
  t.distance_km,
  t.created_at,
  t.user_id,
  t.resting_heart_rate,
  t.hrv_ms,
  t.spo2_pct,
  t.water_ml,
  t.updated_at,
  t.deleted_at,
  t.active_calories,
  t.waist_cm,
  t.chest_cm,
  t.arm_cm,
  t.thigh_cm,
  t.hip_cm,
  t.neck_cm,
  t.source_map,
  t.skeletal_muscle_pct,
  t.fat_free_mass_kg,
  t.subcutaneous_fat_pct,
  t.visceral_fat_index,
  t.body_water_pct,
  t.muscle_mass_kg,
  t.bone_mass_kg,
  t.protein_pct,
  t.bmr_kcal,
  t.metabolic_age
FROM public.body_metrics t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.coach_changes AS
SELECT
  t.id,
  t.user_id,
  t.domain,
  t.target_id,
  t.patch,
  t.accepted_ids,
  t.before_state,
  t.summary,
  t.applied_at,
  t.undone_at
FROM public.coach_changes t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.coach_messages AS
SELECT
  t.id,
  t.thread_id,
  t.user_id,
  t.role,
  t.parts,
  t.position,
  t.created_at
FROM public.coach_messages t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.coach_threads AS
SELECT
  t.id,
  t.user_id,
  t.title,
  t.created_at,
  t.updated_at
FROM public.coach_threads t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.daily_zone_minutes AS
SELECT
  t.user_id,
  t.day,
  t.zone1_sec,
  t.zone2_sec,
  t.zone3_sec,
  t.zone4_sec,
  t.zone5_sec,
  t.computed_at,
  t.max_hr,
  t.resting_hr
FROM public.daily_zone_minutes t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.day_checkins AS
SELECT
  t.id,
  t.user_id,
  t.log_date,
  t.phase,
  t.physical_tiredness,
  t.mental_drain,
  t.barely_moved,
  t.hydration,
  t.late_heavy_meal,
  t.sore_muscles,
  t.journal,
  t.created_at,
  t.updated_at,
  t.deleted_at,
  t.wake_mood,
  t.perceived_recovery,
  t.motivation,
  t.sleep_quality_feel,
  t.resting_soreness,
  t.illness_context,
  t.perceived_recovery_touched,
  t.sleep_quality_feel_touched
FROM public.day_checkins t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- db_query_log: shared reference data, not row-scoped
CREATE VIEW claude_ro.db_query_log AS
SELECT
  t.id,
  t.created_at,
  t.sql_text,
  t.row_count,
  t.duration_ms,
  t.truncated,
  t.ok,
  t.error,
  t.caller_ip
FROM public.db_query_log t;

CREATE VIEW claude_ro.error_events AS
SELECT
  t.id,
  t.user_id,
  t.source,
  t.message,
  t.stack,
  t.url,
  t.user_agent,
  t.created_at
FROM public.error_events t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.exercise_estimates AS
SELECT
  t.id,
  t.user_id,
  t.exercise_id,
  t.exercise_name,
  t.estimated_1rm,
  t.created_at,
  t.updated_at
FROM public.exercise_estimates t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- exercise_gif_cache: shared reference data, not row-scoped
CREATE VIEW claude_ro.exercise_gif_cache AS
SELECT
  t.exercise_name,
  t.gif_url,
  t.image_url,
  t.fetched_at
FROM public.exercise_gif_cache t;

-- exercise_library: shared reference data, not row-scoped
CREATE VIEW claude_ro.exercise_library AS
SELECT
  t.id,
  t.name,
  t.muscles,
  t.equipment,
  t.instructions,
  t.created_by,
  t.exercise_type,
  t.merged_into
FROM public.exercise_library t;

CREATE VIEW claude_ro.exercise_logs AS
SELECT
  t.id,
  t.workout_session_id,
  t.exercise_name,
  t.style_id,
  t.style_name,
  t.estimated_1rm,
  t.target_80,
  t.volume,
  t.avg_reps,
  t.time_to_complete,
  t.muscle_groups,
  t.logged_at,
  t.updated_at,
  t.inter_exercise_rest_sec,
  t.exercise_id,
  t.deleted_at,
  t.exercise_deloaded,
  t.prep_time_sec
FROM public.exercise_logs t
WHERE EXISTS (SELECT 1 FROM public.workout_sessions p WHERE p.id = t.workout_session_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

-- exercise_media: shared reference data, not row-scoped
CREATE VIEW claude_ro.exercise_media AS
SELECT
  t.id,
  t.exercise_name,
  t.gender,
  t.start_url,
  t.end_url,
  t.gif_url,
  t.model_used,
  t.generated_at,
  t.exercise_id
FROM public.exercise_media t;

-- feedback_submissions: withholding "screenshot_data"
CREATE VIEW claude_ro.feedback_submissions AS
SELECT
  t.id,
  t.user_id,
  t.type,
  t.title,
  t.description,
  t.created_at,
  octet_length(t.screenshot_data) AS screenshot_bytes
FROM public.feedback_submissions t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.fitness_tests AS
SELECT
  t.id,
  t.user_id,
  t.test_type,
  t.date,
  t.duration_sec,
  t.distance_m,
  t.avg_hr,
  t.max_hr,
  t.resting_hr,
  t.hrr1_bpm,
  t.vo2max_est,
  t.method,
  t.notes,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.fitness_tests t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.food_items AS
SELECT
  t.id,
  t.user_id,
  t.name,
  t.brand,
  t.serving_size_g,
  t.calories,
  t.protein_g,
  t.carbs_g,
  t.fat_g,
  t.fiber_g,
  t.sugar_g,
  t.sodium_mg,
  t.sat_fat_g,
  t.source,
  t.barcode,
  t.region,
  t.created_at
FROM public.food_items t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.food_logs AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.meal_type_id,
  t.food_item_id,
  t.quantity_multiplier,
  t.logged_at,
  t.updated_at,
  t.deleted_at
FROM public.food_logs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.friendships AS
SELECT
  t.id,
  t.requester_id,
  t.addressee_id,
  t.status,
  t.created_at,
  t.updated_at
FROM public.friendships t
WHERE t.requester_id = 'fe481797-4114-4f59-824d-223e0281823e' OR t.addressee_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.goal_recommendations AS
SELECT
  t.id,
  t.user_id,
  t.created_at,
  t.source,
  t.recommended_steps_goal,
  t.recommended_calories,
  t.recommended_protein_g,
  t.recommended_carbs_g,
  t.recommended_fat_g,
  t.recommended_water_ml,
  t.recommended_activity_level,
  t.reasoning,
  t.insights,
  t.data_quality_note,
  t.status,
  t.applied_at,
  t.dismissed_at
FROM public.goal_recommendations t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.injuries AS
SELECT
  t.id,
  t.user_id,
  t.muscle_name,
  t.notes,
  t.severity,
  t.started_date,
  t.resolved_date,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.injuries t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.meal_types AS
SELECT
  t.id,
  t.user_id,
  t.name,
  t.emoji,
  t.sort_order,
  t.time_start_hour,
  t.time_end_hour,
  t.created_at,
  t.reminders_enabled,
  t.required
FROM public.meal_types t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.mood_logs AS
SELECT
  t.id,
  t.user_id,
  t.log_date,
  t.energy_level,
  t.sleep_quality,
  t.body_state,
  t.sore_muscles,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.mood_logs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.nutrition_targets AS
SELECT
  t.id,
  t.user_id,
  t.calories,
  t.protein_g,
  t.carbs_g,
  t.fat_g,
  t.fiber_g,
  t.updated_at
FROM public.nutrition_targets t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_accel_chunks AS
SELECT
  t.id,
  t.user_id,
  t.started_at,
  t.sample_rate,
  t.n,
  t.steps,
  t.magnitudes,
  t.created_at
FROM public.oura_accel_chunks t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_ble_battery_poll AS
SELECT
  t.id,
  t.user_id,
  t.measured_at,
  t.percent,
  t.charging
FROM public.oura_ble_battery_poll t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_ble_clock_anchors AS
SELECT
  t.id,
  t.user_id,
  t.anchor_ds,
  t.anchor_utc,
  t.created_at,
  t.epoch,
  t.observed_source
FROM public.oura_ble_clock_anchors t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_bucket AS
SELECT
  t.id,
  t.user_id,
  t.tier,
  t.bucket_start_ms,
  t.bucket_start_ds,
  t.local_date,
  t.hr_mean,
  t.hr_min,
  t.hr_max,
  t.hrv_rmssd_ms,
  t.spo2_pct,
  t.perfusion_index,
  t.skin_temp_c,
  t.met_mean,
  t.met_minutes,
  t.motion_mad,
  t.ibi_ms,
  t.sample_count,
  t.updated_at
FROM public.oura_bucket t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_daily AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.readiness_score,
  t.temperature_deviation,
  t.temperature_trend_deviation,
  t.readiness_contributors,
  t.sleep_score,
  t.sleep_contributors,
  t.activity_score,
  t.active_calories,
  t.total_calories,
  t.equivalent_walking_distance,
  t.high_activity_time_sec,
  t.medium_activity_time_sec,
  t.low_activity_time_sec,
  t.sedentary_time_sec,
  t.non_wear_time_sec,
  t.activity_contributors,
  t.synced_at,
  t.stress_high,
  t.recovery_high,
  t.day_summary,
  t.vo2_max,
  t.vascular_age,
  t.pulse_wave_velocity,
  t.resilience_level,
  t.resilience_contributors,
  t.recommended_bedtime_start,
  t.recommended_bedtime_end,
  t.sleep_time_status,
  t.sleep_time_recommendation,
  t.breathing_disturbance_index,
  t.resting_time_sec,
  t.avg_met_minutes,
  t.high_activity_met_minutes,
  t.medium_activity_met_minutes,
  t.low_activity_met_minutes,
  t.source_map
FROM public.oura_daily t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_daily_derived AS
SELECT
  t.id,
  t.user_id,
  t.day,
  t.source,
  t.model_versions,
  t.sleep_score,
  t.sleep_contributors,
  t.readiness_score,
  t.readiness_contributors,
  t.readiness_source,
  t.activity_score,
  t.activity_contributors,
  t.active_calories_est,
  t.training_load_ots,
  t.training_load_high,
  t.recovery_index_hours,
  t.worn_hours_ble,
  t.night_hrv_baseline_ms,
  t.illness_flag,
  t.illness_score,
  t.illness_biomarkers,
  t.daytime_stress_scaled,
  t.stress_high_minutes,
  t.recovery_high_minutes,
  t.chronic_stress_score,
  t.chronic_stress_contributors,
  t.resilience_level,
  t.vascular_age,
  t.pwv,
  t.body_comp,
  t.computed_at,
  t.created_at,
  t.updated_at,
  t.resilience_daily_stress,
  t.resilience_daily_restorative_time,
  t.resilience_daily_sleep_recovery,
  t.resilience_granular,
  t.resilience_confidence,
  t.bdi_derived
FROM public.oura_daily_derived t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_daily_summary AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.sleep_duration_hours,
  t.sleep_efficiency,
  t.deep_sleep_hours,
  t.rem_sleep_hours,
  t.restless_periods,
  t.sleep_latency_sec,
  t.hrv_avg_ms,
  t.rhr_low_bpm,
  t.rhr_avg_bpm,
  t.recovery_index_hours,
  t.temp_mean_c,
  t.temp_dev_c,
  t.met_avg,
  t.hrv_baseline_mean_x8,
  t.hrv_baseline_dev_x8,
  t.rhr_baseline_mean_x8,
  t.rhr_baseline_dev_x8,
  t.temp_baseline_mean_x8,
  t.temp_baseline_dev_x8,
  t.sleep_baseline_mean_x8,
  t.sleep_baseline_dev_x8,
  t.met_baseline_mean_x8,
  t.met_baseline_dev_x8,
  t.n_history,
  t.created_at,
  t.updated_at,
  t.breath_avg_rpm,
  t.breath_baseline_mean_x8,
  t.breath_baseline_dev_x8
FROM public.oura_daily_summary t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_daytime_hrv_model AS
SELECT
  t.user_id,
  t.intercept,
  t.hr_coef,
  t.temp_coef,
  t.residual_std,
  t.n_samples,
  t.fitted_at
FROM public.oura_daytime_hrv_model t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_heartrate AS
SELECT
  t.id,
  t.user_id,
  t.timestamp,
  t.bpm,
  t.source,
  t.updated_at
FROM public.oura_heartrate t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_raw_samples AS
SELECT
  t.id,
  t.user_id,
  t.ring_timestamp_ds,
  t.tag,
  t.event_name,
  t.body_hex,
  t.decoded,
  t.recorded_at,
  t.measured_at,
  t.epoch
FROM public.oura_raw_samples t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_tags AS
SELECT
  t.id,
  t.user_id,
  t.oura_id,
  t.source,
  t.tag_type,
  t.custom_name,
  t.comment,
  t.mood,
  t.start_day,
  t.end_day,
  t.start_time,
  t.end_time,
  t.synced_at
FROM public.oura_tags t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- oura_tokens: withholding "personal_access_token", "access_token", "refresh_token", "webhook_signing_key"
CREATE VIEW claude_ro.oura_tokens AS
SELECT
  t.user_id,
  t.expires_at,
  t.scope,
  t.created_at,
  t.updated_at,
  t.oura_user_id,
  (t.personal_access_token IS NOT NULL) AS has_pat,
  (t.access_token IS NOT NULL) AS has_oauth_access,
  (t.refresh_token IS NOT NULL) AS has_oauth_refresh,
  (t.webhook_signing_key IS NOT NULL) AS has_webhook_key
FROM public.oura_tokens t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.oura_workouts AS
SELECT
  t.id,
  t.user_id,
  t.day,
  t.activity,
  t.start_datetime,
  t.end_datetime,
  t.calories,
  t.distance_m,
  t.intensity,
  t.source,
  t.reviewed,
  t.created_at
FROM public.oura_workouts t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.personal_records AS
SELECT
  t.id,
  t.user_id,
  t.exercise_name,
  t.estimated_1rm,
  t.achieved_at,
  t.exercise_id
FROM public.personal_records t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.phase_sets AS
SELECT
  t.id,
  t.user_id,
  t.name,
  t.is_default,
  t.created_at,
  t.owner_program_id,
  t.template_base_name
FROM public.phase_sets t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.prescribed_runs AS
SELECT
  t.id,
  t.user_id,
  t.plan_id,
  t.date,
  t.run_type,
  t.duration_min,
  t.distance_km,
  t.target_hr_low,
  t.target_hr_high,
  t.target_zone_ids,
  t.rationale,
  t.gate_action,
  t.status,
  t.activity_log_id,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.prescribed_runs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.program_phases AS
SELECT
  t.id,
  t.program_id,
  t.position,
  t.name,
  t.duration_cycles,
  t.phase_type,
  t.primary_style_id,
  t.secondary_style_id,
  t.phase_set_id
FROM public.program_phases t
WHERE EXISTS (SELECT 1 FROM public.phase_sets ps WHERE ps.id = t.phase_set_id AND ps.user_id = 'fe481797-4114-4f59-824d-223e0281823e') OR EXISTS (SELECT 1 FROM public.programs p WHERE p.id = t.program_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.program_sessions AS
SELECT
  t.id,
  t.program_id,
  t.name,
  t.position,
  t.icon,
  t.updated_at,
  t.time_budget_minutes
FROM public.program_sessions t
WHERE EXISTS (SELECT 1 FROM public.programs p WHERE p.id = t.program_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.program_volume_targets AS
SELECT
  t.id,
  t.program_id,
  t.muscle_group,
  t.target_sets_per_week
FROM public.program_volume_targets t
WHERE EXISTS (SELECT 1 FROM public.programs p WHERE p.id = t.program_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.programs AS
SELECT
  t.id,
  t.name,
  t.is_active,
  t.created_at,
  t.updated_at,
  t.user_id,
  t.phase_mode,
  t.started_at,
  t.sessions_per_cycle,
  t.early_deload_week_start,
  t.phase_set_id,
  t.total_weeks,
  t.cycle_anchor_at,
  t.training_goal,
  t.auto_apply_prescriptions
FROM public.programs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.progression_styles AS
SELECT
  t.id,
  t.name,
  t.user_id,
  t.updated_at
FROM public.progression_styles t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- push_subscriptions: withholding "endpoint", "p256dh", "auth"
CREATE VIEW claude_ro.push_subscriptions AS
SELECT
  t.id,
  t.user_id,
  t.created_at,
  (t.endpoint IS NOT NULL) AS has_subscription
FROM public.push_subscriptions t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.rr_intervals AS
SELECT
  t.id,
  t.user_id,
  t.at,
  t.rr_ms,
  t.source
FROM public.rr_intervals t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.running_baselines AS
SELECT
  t.id,
  t.user_id,
  t.plan_id,
  t.vo2max,
  t.max_hr,
  t.resting_hr,
  t.threshold_hr,
  t.weekly_base_minutes,
  t.easy_pace_sec_per_km,
  t.created_at
FROM public.running_baselines t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.running_plans AS
SELECT
  t.id,
  t.user_id,
  t.goal_kind,
  t.target_distance_km,
  t.target_date,
  t.framework_key,
  t.fitness_snapshot,
  t.is_active,
  t.created_at,
  t.updated_at,
  t.time_per_session_minutes
FROM public.running_plans t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.saved_meal_items AS
SELECT
  t.id,
  t.saved_meal_id,
  t.food_item_id,
  t.quantity_multiplier
FROM public.saved_meal_items t
WHERE EXISTS (SELECT 1 FROM public.saved_meals sm WHERE sm.id = t.saved_meal_id AND sm.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.saved_meals AS
SELECT
  t.id,
  t.user_id,
  t.name,
  t.created_at
FROM public.saved_meals t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.scale_raw_samples AS
SELECT
  t.id,
  t.user_id,
  t.measured_at,
  t.raw_hex,
  t.decoded,
  t.status,
  t.created_at
FROM public.scale_raw_samples t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.schedule_days AS
SELECT
  t.schedule_id,
  t.day_of_week,
  t.session_id,
  t.updated_at
FROM public.schedule_days t
WHERE EXISTS (SELECT 1 FROM public.schedules s JOIN public.programs p ON p.id = s.program_id WHERE s.id = t.schedule_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.schedules AS
SELECT
  t.id,
  t.program_id,
  t.type,
  t.rest_after_n,
  t.updated_at,
  t.reminder_enabled,
  t.reminder_time
FROM public.schedules t
WHERE EXISTS (SELECT 1 FROM public.programs p WHERE p.id = t.program_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

-- schema_migrations: shared reference data, not row-scoped
CREATE VIEW claude_ro.schema_migrations AS
SELECT
  t.filename,
  t.applied_at
FROM public.schema_migrations t;

CREATE VIEW claude_ro.season_results AS
SELECT
  t.id,
  t.season_id,
  t.user_id,
  t.rank,
  t.sessions,
  t.volume_kg,
  t.badge_label
FROM public.season_results t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- seasons: shared reference data, not row-scoped
CREATE VIEW claude_ro.seasons AS
SELECT
  t.id,
  t.label,
  t.start_date,
  t.end_date
FROM public.seasons t;

CREATE VIEW claude_ro.session_exercises AS
SELECT
  t.id,
  t.session_id,
  t.exercise_name,
  t.style_id,
  t.muscle_groups,
  t.position,
  t.exercise_role,
  t.updated_at,
  t.exercise_id,
  t.superset_group
FROM public.session_exercises t
WHERE EXISTS (SELECT 1 FROM public.program_sessions ps JOIN public.programs p ON p.id = ps.program_id WHERE ps.id = t.session_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.session_periodization AS
SELECT
  t.id,
  t.user_id,
  t.program_session_id,
  t.phase,
  t.phase_started_at,
  t.sessions_in_phase,
  t.baseline_complete,
  t.baseline_1rm,
  t.prescription,
  t.prescription_generated_at,
  t.prescription_expires_at,
  t.prescription_status,
  t.last_session_ran_prescription,
  t.pending_transition,
  t.pre_emergency_deload_phase,
  t.updated_at
FROM public.session_periodization t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.set_hr_stats AS
SELECT
  t.set_log_id,
  t.user_id,
  t.workout_session_id,
  t.exercise_log_id,
  t.exercise_id,
  t.exercise_name,
  t.phase_type,
  t.set_number,
  t.intensity_pct,
  t.planned_pct,
  t.rest_taken_sec,
  t.planned_rest_sec,
  t.logged_at,
  t.peak_bpm,
  t.avg_bpm,
  t.bpm_at_end,
  t.drop_30s,
  t.drop_60s,
  t.drop_90s,
  t.drop_120s,
  t.trough_bpm,
  t.sec_to_preset,
  t.recovered_preset,
  t.sec_to_resting,
  t.recovered_resting,
  t.pct_hrr_at_rest_end,
  t.sec_to_hrr50,
  t.rest_adequate,
  t.readings_count,
  t.coverage_ok,
  t.source,
  t.computed_at,
  t.planned_reps
FROM public.set_hr_stats t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.set_logs AS
SELECT
  t.id,
  t.exercise_log_id,
  t.set_number,
  t.weight_kg,
  t.reps,
  t.set_time_sec,
  t.rest_time_sec,
  t.intensity_pct,
  t.use_for_1rm,
  t.updated_at,
  t.set_start_ms,
  t.set_end_ms,
  t.rpe,
  t.deleted_at,
  t.planned_pct,
  t.planned_rest_sec,
  t.planned_reps
FROM public.set_logs t
WHERE EXISTS (SELECT 1 FROM public.exercise_logs e JOIN public.workout_sessions p ON p.id = e.workout_session_id WHERE e.id = t.exercise_log_id AND p.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.sleep_sessions AS
SELECT
  t.id,
  t.user_id,
  t.date,
  t.sleep_start,
  t.sleep_end,
  t.duration_hours,
  t.deep_sleep_hours,
  t.rem_sleep_hours,
  t.light_sleep_hours,
  t.awake_hours,
  t.created_at,
  t.updated_at,
  t.oura_id,
  t.efficiency,
  t.onset_latency_sec,
  t.average_hrv_ms,
  t.avg_heart_rate,
  t.lowest_heart_rate,
  t.restless_periods,
  t.sleep_score,
  t.respiratory_rate,
  t.sleep_phase_5_min,
  t.time_in_bed_hours,
  t.source_map
FROM public.sleep_sessions t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.step_live_windows AS
SELECT
  t.id,
  t.user_id,
  t.start_ds,
  t.end_ds,
  t.steps,
  t.source,
  t.created_at
FROM public.step_live_windows t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.style_sets AS
SELECT
  t.id,
  t.style_id,
  t.set_number,
  t.pct,
  t.reps,
  t.rest_sec,
  t.use_for_1rm,
  t.updated_at
FROM public.style_sets t
WHERE EXISTS (SELECT 1 FROM public.progression_styles ps WHERE ps.id = t.style_id AND ps.user_id = 'fe481797-4114-4f59-824d-223e0281823e');

CREATE VIEW claude_ro.supplement_logs AS
SELECT
  t.id,
  t.supplement_id,
  t.user_id,
  t.log_date,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.supplement_logs t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.supplements AS
SELECT
  t.id,
  t.user_id,
  t.name,
  t.dose,
  t.reminder_enabled,
  t.reminder_time,
  t.sort_order,
  t.active,
  t.created_at,
  t.updated_at,
  t.deleted_at
FROM public.supplements t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.user_stats AS
SELECT
  t.user_id,
  t.total_sessions,
  t.total_volume_kg,
  t.total_sets,
  t.updated_at
FROM public.user_stats t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

-- users: withholding "password_hash"
CREATE VIEW claude_ro.users AS
SELECT
  t.email,
  t.name,
  t.is_active,
  t.created_at,
  t.oauth_sub,
  t.id,
  t.display_name,
  t.height_cm,
  t.date_of_birth,
  t.weight_goal_kg,
  t.avatar,
  t.is_admin,
  t.timezone,
  t.food_region,
  t.sex,
  t.steps_goal,
  t.steps_goal_type,
  t.sleep_goal_hours,
  t.calorie_goal,
  t.calorie_goal_type,
  t.water_goal_ml,
  t.water_goal_type,
  t.target_weight_kg,
  t.target_bf_pct,
  t.friend_code,
  t.equipped_title,
  t.activity_level,
  t.fitness_goal,
  t.last_goal_review_at,
  t.timing_baseline_date
FROM public.users t
WHERE t.id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.workout_hr_stats AS
SELECT
  t.workout_session_id,
  t.user_id,
  t.avg_bpm,
  t.peak_bpm,
  t.hrr1_best,
  t.workout_hrv_ms,
  t.readings_count,
  t.source,
  t.computed_at
FROM public.workout_hr_stats t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

CREATE VIEW claude_ro.workout_sessions AS
SELECT
  t.id,
  t.session_id,
  t.session_name,
  t.started_at,
  t.completed_at,
  t.user_id,
  t.updated_at,
  t.phase_id,
  t.is_early_deload,
  t.phase_type,
  t.program_session_id,
  t.hr_synced_at,
  t.was_override,
  t.intensity_mode,
  t.session_rpe,
  t.warmup_ended_at,
  t.deleted_at
FROM public.workout_sessions t
WHERE t.user_id = 'fe481797-4114-4f59-824d-223e0281823e';

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'claude_readonly') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA claude_ro TO claude_readonly';
    EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA claude_ro TO claude_readonly';
    EXECUTE 'ALTER ROLE claude_readonly SET search_path = claude_ro';
  END IF;
END $$;
